### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by elementalPRESS** [isaacplmann/ngx-contextmenu#222]
Hi,

I'm just wondering if this package is still alive. In general it still works with Angular 11 but there where a lot of missing peer dependencies during compilation. It would be so great if the package.json could be updated.

Best regards
Lars

**Comment by isaacplmann** [comment]
Angular 12 support in 6.0.0

**Comment by FieteO** [comment]
From my point of view there is a gap for Angular 11 in the dependencies between 5.4 and 6.0. When you are on Angular 11, `angular/common: 11.2.113` needs at least cdk > 10.
This library requires cdk < 10 in `5.4.0` and cdk 12 in `6.0.0`. However you can't update to cdk 12 because it requires Angular 12.
