### ISSUE TITLE
Downgrading to angular1.5

### ISSUE THREAD

**Issue by deephakdd** [isaacplmann/ngx-contextmenu#52]
Hi ,

I have used the ngx-contextmenu in my application which is developed on Angular4.

now i need to downgrade my entire application to angular1.5 .

i am facing an issue with ngx-xontextmenu after downgrading.

i am getting the following error

View Container not found! ngUpgrade needs to manually set this via setRootViewContainer.

i tried injecting the injection service and using the setRootViewContainer , i am passing the component which uses the ngx-contextmenu as viewChild ,

but i ended up getting another error 
hostView is not defined ,

Can you please tell me on what component must be passed 

Thanks

**Comment by isaacplmann** [comment]
I've never used this library in a `ngUpgrade` environment, but I might be able to guide you in the right direction.  `ngx-contextmenu` uses [`InjectionService`](https://github.com/isaacplmann/ngx-contextmenu/blob/master/src/lib/injection/injection.service.ts#L49) to put the context menu on the page.  This is a service I pulled in from the `ngx-charts` library.  Since `ngUpgrade` doesn't provide an `ApplicationRef` you need to manually run the code below on your top level `AppComponent`.  Let me know if this works for you.

```ts
  constructor(
    private vcr: ViewContainerRef,
    private contextMenuInjectorService: ContextMenuInjectorService) {
    this.contextMenuInjectorService.injectionService.setRootViewContainer(vcr);
  }
```

**Comment by deephakdd** [comment]
Hi Issac,

Thanks ,

It works like a charm

**Comment by isaacplmann** [comment]
FYI, the contextMenuInjectorService is replaced by @angular/cdk in version `2.0.0-beta.1`
